base_url : https://www.guvi.in/
browser : chrome
username : vidhyasarjn@gmail.com
password : YYYYYYYYYYYY
invalid_username : vidhyas@gmail.com
invalid_password : XXXXXXXXXX
dashboard_url: https://www.zenclass.in/dashboard
title: HCL GUVI | Learn to code in your native language
error_message_invalid : Incorrect Email or Password

